# Generated by Django 4.0.10 on 2025-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Объем двигателя'),
        ),
    ]
